### PR TITLE
Improve the directory structure of the NLP notebooks

### PR DESCRIPTION
**Pull request by anjleeg-gcai**
First attempt restructuring the NLP notebooks to fit a better structure.

Note these changes also pull some of the latest changes from the base HF repository.

### CODE REVIEW

**Comment by anjleeg-gcai** [comment]
[log-url-git-github-com-graphcore-Graphcore-HuggingFace-fork-git-2023-02-10 17/30/03.250177.log](https://github.com/gradient-ai/Graphcore-HuggingFace/files/10709866/log-url-git-github-com-graphcore-Graphcore-HuggingFace-fork-git-2023-02-10.17.30.03.250177.log)

Adding url test results, checked all of the website links manually, not sure why the first one is failing because i fixed that and tested it manually and it does work.

**Comment by anjleeg-gcai** [comment]
[log-url-git-github-com-graphcore-Graphcore-HuggingFace-fork-git-2023-02-10 17/39/23.387564.log](https://github.com/gradient-ai/Graphcore-HuggingFace/files/10709906/log-url-git-github-com-graphcore-Graphcore-HuggingFace-fork-git-2023-02-10.17.39.23.387564.log)

Retested and now passing after last change.

**Review by payoto — APPROVED** [review]
LGTM

**Comment by payoto** [comment]
Thanks for doing the changes 👍

**Pull request merged**
